// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://sngjcqqbvmpfwigfwigb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNuZ2pjcXFidm1wZndpZ2Z3aWdiIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Njg5NjQ1ODMsImV4cCI6MjA4NDU0MDU4M30.nTgic9tKpP-NVJc4tTa9eh865NS3oucW9WBbKCB-a80";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});